version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: employlaw-surrealdb
    command: >
      start
      --log trace
      --user root
      --pass root
      --bind 0.0.0.0:8000
      memory
    ports:
      - '8000:8000'
    environment:
      - SURREAL_LOG=trace
      - SURREAL_USER=root
      - SURREAL_PASS=root
    volumes:
      - surrealdb_data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - surrealdb-network

volumes:
  surrealdb_data:
    driver: local

networks:
  surrealdb-network:
    driver: bridge
